local DoctorioUI, E, L, V, P, G = unpack((select(2, ...)))

-- ElvUI Layout
function DoctorioUI:Setup_ElvUI()
	----------------------------------------------------------------------
	----------------------- Do Not Touch This Part -----------------------
	----------------------------------------------------------------------
	E.db.convertPages = true
	E.db.movers = E.db.movers or {}
	E.db.actionbar.bar6.enabled = false -- Should be disabled
	----------------------------------------------------------------------
	----------------------- Custom Texts Creation ------------------------
	----------------------------------------------------------------------
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"] = E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"] or {}
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"] = E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"] or {}
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"] = E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"] or {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"] = E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"] or {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"] = E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"] or {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"] = E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"] or {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"] = E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"] or {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"] = E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"] or {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"] = E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"] or {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"] = E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"] or {}
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"] = E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"] or {}
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"] = E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"] or {}
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"] = E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"] or {}
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"] = E.db["unitframe"]["units"]["player"]["customTexts"]["HP"] or {}
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"] = E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"] or {}
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"] = E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"] or {}
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"] = E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"] or {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"] = E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"] or {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"] = E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"] or {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"] = E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"] or {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"] = E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"] or {}
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"] = E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"] or {}
	----------------------------------------------------------------------
	----------------------- Custom DataText Data -------------------------
	----------------------------------------------------------------------
	E.db["datatexts"]["panels"]["Top Panel (Left)"]["battleground"] = false
	E.db["datatexts"]["panels"]["Top Panel (Left)"]["enable"] = true
	E.db["datatexts"]["panels"]["Top Panel (Left)"][1] = "Durability"
	E.db["datatexts"]["panels"]["Top Panel (Left)"][2] = "System"
	E.db["datatexts"]["panels"]["Top Panel (Right)"]["battleground"] = false
	E.db["datatexts"]["panels"]["Top Panel (Right)"]["enable"] = true
	E.db["datatexts"]["panels"]["Top Panel (Right)"][1] = "Volume"
	E.db["datatexts"]["panels"]["Top Panel (Right)"][4] = "Time"
	E.db["movers"]["DTPanelTop Panel (Left)Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,0,0"
	E.db["movers"]["DTPanelTop Panel (Right)Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,0"
	if E:IsAddOnEnabled('BugSack') then
		E.db["datatexts"]["panels"]["Top Panel (Right)"][2] = "LDB_BugSack"
	end
	if E:IsAddOnEnabled('WIM') then
		E.db["datatexts"]["panels"]["Top Panel (Left)"][3] = "LDB_WIM"
	end
	if E:IsAddOnEnabled('WeakAuras') then
		E.db["datatexts"]["panels"]["Top Panel (Right)"][3] = "LDB_WeakAuras"
	end
	----------------------------------------------------------------------
	----------------------- Copy/Paste Export Here -----------------------
	----------------------------------------------------------------------
	E.db["actionbar"]["bar1"]["buttonSize"] = 30
	E.db["actionbar"]["bar1"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar1"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar1"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar1"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["paging"]["DEATHKNIGHT"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["DEMONHUNTER"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["DRUID"] = "[mod:ctrl] 10; [bonusbar:1,nostealth] 9; [bonusbar:1,stealth] 9; [bonusbar:3] 5; [bonusbar:4] 6;"
	E.db["actionbar"]["bar1"]["paging"]["EVOKER"] = "[bonusbar:1] 15; [mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["HUNTER"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["MAGE"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["MONK"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["PALADIN"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["PRIEST"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["ROGUE"] = "[bonusbar:1] 7; [mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["SHAMAN"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["WARLOCK"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["paging"]["WARRIOR"] = "[mod:ctrl] 10;"
	E.db["actionbar"]["bar1"]["professionQuality"]["scale"] = 0.4
	E.db["actionbar"]["bar10"]["alpha"] = 0
	E.db["actionbar"]["bar10"]["buttonSize"] = 30
	E.db["actionbar"]["bar10"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar10"]["clickThrough"] = true
	E.db["actionbar"]["bar10"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar10"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["enabled"] = true
	E.db["actionbar"]["bar10"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar10"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar13"]["buttonSize"] = 30
	E.db["actionbar"]["bar13"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar13"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar13"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar13"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar13"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar13"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar13"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar14"]["buttonSize"] = 30
	E.db["actionbar"]["bar14"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar14"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar14"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar14"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar14"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar14"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar14"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar15"]["buttonSize"] = 30
	E.db["actionbar"]["bar15"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar15"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar15"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar15"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar15"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar15"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar15"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["buttonSize"] = 30
	E.db["actionbar"]["bar2"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar2"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar2"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["enabled"] = true
	E.db["actionbar"]["bar2"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar2"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["visibility"] = "[petbattle] hide; show"
	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["buttonSize"] = 30
	E.db["actionbar"]["bar3"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar3"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar3"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar3"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar3"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["visibility"] = "[petbattle] hide; show"
	E.db["actionbar"]["bar4"]["backdrop"] = false
	E.db["actionbar"]["bar4"]["buttonSize"] = 30
	E.db["actionbar"]["bar4"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar4"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar4"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar4"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar4"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["point"] = "BOTTOMLEFT"
	E.db["actionbar"]["bar4"]["visibility"] = "[petbattle] hide; show"
	E.db["actionbar"]["bar5"]["buttons"] = 12
	E.db["actionbar"]["bar5"]["buttonSize"] = 30
	E.db["actionbar"]["bar5"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar5"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar5"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar5"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["enabled"] = false
	E.db["actionbar"]["bar5"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar5"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["visibility"] = "[petbattle] hide; show"
	E.db["actionbar"]["bar6"]["buttonSize"] = 30
	E.db["actionbar"]["bar6"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar6"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar6"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar6"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar6"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["visibility"] = "[petbattle] hide; show"
	E.db["actionbar"]["bar7"]["buttonSize"] = 30
	E.db["actionbar"]["bar7"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar7"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar7"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar7"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar7"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["paging"]["ROGUE"] = ""
	E.db["actionbar"]["bar8"]["alpha"] = 0
	E.db["actionbar"]["bar8"]["buttonSize"] = 30
	E.db["actionbar"]["bar8"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar8"]["clickThrough"] = true
	E.db["actionbar"]["bar8"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar8"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar8"]["enabled"] = true
	E.db["actionbar"]["bar8"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar8"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar8"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar8"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["buttonSize"] = 30
	E.db["actionbar"]["bar9"]["buttonSpacing"] = 1
	E.db["actionbar"]["bar9"]["countFont"] = "Expressway"
	E.db["actionbar"]["bar9"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["bar9"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["macroFont"] = "Expressway"
	E.db["actionbar"]["bar9"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["paging"]["DRUID"] = ""
	E.db["actionbar"]["barPet"]["buttonSize"] = 36
	E.db["actionbar"]["barPet"]["buttonSpacing"] = 4
	E.db["actionbar"]["barPet"]["buttonsPerRow"] = 5
	E.db["actionbar"]["barPet"]["countFont"] = "Expressway"
	E.db["actionbar"]["barPet"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["barPet"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["checkFocusCast"] = false
	E.db["actionbar"]["checkSelfCast"] = false
	E.db["actionbar"]["extraActionButton"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["extraActionButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["font"] = "Expressway"
	E.db["actionbar"]["fontOutline"] = "OUTLINE"
	E.db["actionbar"]["microbar"]["mouseover"] = true
	E.db["actionbar"]["stanceBar"]["enabled"] = false
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "Expressway"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["auras"]["buffs"]["countFont"] = "Expressway"
	E.db["auras"]["buffs"]["countFontOutline"] = "OUTLINE"
	E.db["auras"]["buffs"]["countFontSize"] = 12
	E.db["auras"]["buffs"]["horizontalSpacing"] = 2
	E.db["auras"]["buffs"]["size"] = 35
	E.db["auras"]["buffs"]["timeFont"] = "Expressway"
	E.db["auras"]["buffs"]["timeFontOutline"] = "OUTLINE"
	E.db["auras"]["buffs"]["timeFontSize"] = 12
	E.db["auras"]["debuffs"]["countFont"] = "Expressway"
	E.db["auras"]["debuffs"]["countFontOutline"] = "OUTLINE"
	E.db["auras"]["debuffs"]["countFontSize"] = 12
	E.db["auras"]["debuffs"]["size"] = 40
	E.db["auras"]["debuffs"]["timeFont"] = "Expressway"
	E.db["auras"]["debuffs"]["timeFontOutline"] = "OUTLINE"
	E.db["auras"]["debuffs"]["timeFontSize"] = 12
	E.db["bags"]["bagSize"] = 42
	E.db["bags"]["bagWidth"] = 474
	E.db["bags"]["bankSize"] = 42
	E.db["bags"]["bankWidth"] = 474
	E.db["bags"]["countFont"] = "Expressway"
	E.db["bags"]["countFontSize"] = 12
	E.db["bags"]["itemLevelCustomColorEnable"] = true
	E.db["bags"]["itemLevelFont"] = "Expressway"
	E.db["bags"]["itemLevelFontSize"] = 12
	E.db["bags"]["scrapIcon"] = true
	E.db["bags"]["split"]["bag1"] = true
	E.db["bags"]["split"]["bag2"] = true
	E.db["bags"]["split"]["bag3"] = true
	E.db["bags"]["split"]["bag4"] = true
	E.db["bags"]["split"]["bagSpacing"] = 7
	E.db["bags"]["split"]["player"] = true
	E.db["chat"]["editBoxPosition"] = "ABOVE_CHAT"
	E.db["chat"]["font"] = "Expressway"
	E.db["chat"]["fontSize"] = 12
	E.db["chat"]["panelColor"]["a"] = 0.80000001192093
	E.db["chat"]["panelColor"]["b"] = 0.039215687662363
	E.db["chat"]["panelColor"]["g"] = 0.039215687662363
	E.db["chat"]["panelColor"]["r"] = 0.039215687662363
	E.db["chat"]["panelHeight"] = 285
	E.db["chat"]["panelHeightRight"] = 372
	E.db["chat"]["panelWidth"] = 435
	E.db["chat"]["panelWidthRight"] = 200
	E.db["chat"]["separateSizes"] = true
	E.db["chat"]["tabFont"] = "Expressway"
	E.db["chat"]["tabSelector"] = "NONE"
	E.db["chat"]["tabSelectorColor"]["b"] = 0.49803924560547
	E.db["chat"]["tabSelectorColor"]["g"] = 0.57647061347961
	E.db["chat"]["tabSelectorColor"]["r"] = 0.20000001788139
	E.db["chat"]["timeStampFormat"] = "%H:%M "
	E.db["cooldown"]["targetAura"] = false
	E.db["databars"]["azerite"]["enable"] = false
	E.db["databars"]["experience"]["enable"] = false
	E.db["databars"]["honor"]["enable"] = false
	E.db["databars"]["threat"]["enable"] = false
	E.db["databars"]["threat"]["height"] = 24
	E.db["databars"]["threat"]["width"] = 472
	E.db["datatexts"]["font"] = "Expressway"
	E.db["datatexts"]["panels"]["LeftChatDataPanel"]["enable"] = false
	E.db["datatexts"]["panels"]["LeftChatDataPanel"][3] = "QuickJoin"
	E.db["datatexts"]["panels"]["RightChatDataPanel"]["enable"] = false
	E.db["datatexts"]["panels"]["Top Panel (Left)"]["battleground"] = false
	E.db["datatexts"]["panels"]["Top Panel (Left)"]["enable"] = true
	E.db["datatexts"]["panels"]["Top Panel (Left)"][1] = "Durability"
	E.db["datatexts"]["panels"]["Top Panel (Left)"][2] = "System"
	E.db["datatexts"]["panels"]["Top Panel (Left)"][3] = "LDB_WIM"
	E.db["datatexts"]["panels"]["Top Panel (Right)"]["battleground"] = false
	E.db["datatexts"]["panels"]["Top Panel (Right)"]["enable"] = true
	E.db["datatexts"]["panels"]["Top Panel (Right)"][1] = "Volume"
	E.db["datatexts"]["panels"]["Top Panel (Right)"][2] = "LDB_BugSack"
	E.db["datatexts"]["panels"]["Top Panel (Right)"][3] = "LDB_WeakAuras"
	E.db["datatexts"]["panels"]["Top Panel (Right)"][4] = "Time"
	E.db["general"]["addonCompartment"]["fontSize"] = 20
	E.db["general"]["addonCompartment"]["hide"] = true
	E.db["general"]["addonCompartment"]["size"] = 20
	E.db["general"]["afk"] = false
	E.db["general"]["afkChat"] = false
	E.db["general"]["altPowerBar"]["font"] = "Expressway"
	E.db["general"]["autoRepair"] = "GUILD"
	E.db["general"]["bonusObjectivePosition"] = "AUTO"
	E.db["general"]["bottomPanel"] = false
	E.db["general"]["font"] = "Expressway"
	E.db["general"]["itemLevel"]["itemLevelFont"] = "Expressway"
	E.db["general"]["loginmessage"] = false
	E.db["general"]["lootRoll"]["spacing"] = 3
	E.db["general"]["lootRoll"]["style"] = "fullbar"
	E.db["general"]["lootRoll"]["width"] = 357
	E.db["general"]["minimap"]["icons"]["classHall"]["position"] = "BOTTOMRIGHT"
	E.db["general"]["minimap"]["icons"]["crafting"]["scale"] = 2
	E.db["general"]["minimap"]["icons"]["crafting"]["xOffset"] = -2
	E.db["general"]["minimap"]["icons"]["crafting"]["yOffset"] = -35
	E.db["general"]["minimap"]["icons"]["difficulty"]["scale"] = 0.8
	E.db["general"]["minimap"]["icons"]["difficulty"]["xOffset"] = 11
	E.db["general"]["minimap"]["icons"]["difficulty"]["yOffset"] = -5
	E.db["general"]["minimap"]["icons"]["mail"]["scale"] = 2
	E.db["general"]["minimap"]["icons"]["mail"]["texture"] = "Mail1"
	E.db["general"]["minimap"]["icons"]["mail"]["xOffset"] = -2
	E.db["general"]["minimap"]["icons"]["mail"]["yOffset"] = 2
	E.db["general"]["minimap"]["size"] = 200
	E.db["general"]["objectiveFrameAutoHide"] = false
	E.db["general"]["objectiveFrameHeight"] = 400
	E.db["general"]["questRewardMostValueIcon"] = false
	E.db["general"]["questXPPercent"] = false
	E.db["general"]["smoothingAmount"] = 0.8
	E.db["general"]["stickyFrames"] = false
	E.db["general"]["talkingHeadFrameBackdrop"] = true
	E.db["general"]["talkingHeadFrameScale"] = 1
	E.db["general"]["totems"]["growthDirection"] = "HORIZONTAL"
	E.db["general"]["totems"]["size"] = 50
	E.db["general"]["totems"]["spacing"] = 8
	E.db["general"]["valuecolor"]["b"] = 0.49803924560547
	E.db["general"]["valuecolor"]["g"] = 0.57647061347961
	E.db["general"]["valuecolor"]["r"] = 0.20000001788139
	E.db["layoutSetting"] = "healer"
	E.db["movers"]["AlertFrameMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-478,-349"
	E.db["movers"]["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,0,-60"
	E.db["movers"]["ArenaHeaderMover"] = "TOPLEFT,UIParent,TOPLEFT,391,-364"
	E.db["movers"]["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-294"
	E.db["movers"]["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-294"
	E.db["movers"]["BossBannerMover"] = "TOP,ElvUIParent,TOP,0,-126"
	E.db["movers"]["BossButton"] = "BOTTOM,UIParent,BOTTOM,-284,511"
	E.db["movers"]["BossHeaderMover"] = "TOPLEFT,UIParent,TOPLEFT,389,-284"
	E.db["movers"]["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-237,-40"
	E.db["movers"]["DebuffsMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-237,-197"
	E.db["movers"]["DTPanelTop Panel (Left)Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,0,0"
	E.db["movers"]["DTPanelTop Panel (Right)Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,0"
	E.db["movers"]["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4"
	E.db["movers"]["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,2"
	E.db["movers"]["ElvAB_10"] = "TOPLEFT,UIParent,TOPLEFT,0,-21"
	E.db["movers"]["ElvAB_13"] = "BOTTOM,UIParent,BOTTOM,216,447"
	E.db["movers"]["ElvAB_14"] = "BOTTOM,UIParent,BOTTOM,216,417"
	E.db["movers"]["ElvAB_15"] = "BOTTOM,UIParent,BOTTOM,215,388"
	E.db["movers"]["ElvAB_2"] = "BOTTOM,UIParent,BOTTOM,0,33"
	E.db["movers"]["ElvAB_3"] = "BOTTOM,UIParent,BOTTOM,0,64"
	E.db["movers"]["ElvAB_4"] = "BOTTOM,UIParent,BOTTOM,0,95"
	E.db["movers"]["ElvAB_5"] = "TOP,UIParent,TOP,216,-426"
	E.db["movers"]["ElvAB_6"] = "TOP,UIParent,TOP,215,-456"
	E.db["movers"]["ElvAB_7"] = "TOP,UIParent,TOP,216,-485"
	E.db["movers"]["ElvAB_8"] = "TOPLEFT,UIParent,TOPLEFT,0,-21"
	E.db["movers"]["ElvAB_9"] = "BOTTOM,UIParent,BOTTOM,216,506"
	E.db["movers"]["ElvUF_AssistMover"] = "TOPLEFT,UIParent,TOPLEFT,423,-407"
	E.db["movers"]["ElvUF_FocusCastbarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,365,-220"
	E.db["movers"]["ElvUF_FocusMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,365,-220"
	E.db["movers"]["ElvUF_PartyMover"] = "BOTTOM,ElvUIParent,BOTTOM,310,2"
	E.db["movers"]["ElvUF_PetCastbarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,466"
	E.db["movers"]["ElvUF_PetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,457"
	E.db["movers"]["ElvUF_PlayerCastbarMover"] = "BOTTOM,UIParent,BOTTOM,0,265"
	E.db["movers"]["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,127"
	E.db["movers"]["ElvUF_Raid1Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-202,2"
	E.db["movers"]["ElvUF_Raid2Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-204,2"
	E.db["movers"]["ElvUF_Raid3Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-206,2"
	E.db["movers"]["ElvUF_TankMover"] = "TOPLEFT,UIParent,TOPLEFT,418,-328"
	E.db["movers"]["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,218"
	E.db["movers"]["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,178"
	E.db["movers"]["ElvUF_TargetTargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,238"
	E.db["movers"]["ElvUIBagMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,4,289"
	E.db["movers"]["ElvUIBankMover"] = "BOTTOMLEFT,LeftChatPanel,BOTTOMLEFT,0,27"
	E.db["movers"]["EventToastMover"] = "TOP,ElvUIParent,TOP,0,-150"
	E.db["movers"]["ExperienceBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,43"
	E.db["movers"]["GMMover"] = "TOPLEFT,UIParent,TOPLEFT,350,0"
	E.db["movers"]["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-251"
	E.db["movers"]["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,1"
	E.db["movers"]["LootFrameMover"] = "TOP,UIParent,TOP,257,-284"
	E.db["movers"]["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,490"
	E.db["movers"]["MawBuffsBelowMinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,-290"
	E.db["movers"]["MicrobarMover"] = "TOP,UIParent,TOP,-282,0"
	E.db["movers"]["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,-23"
	E.db["movers"]["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96"
	E.db["movers"]["MirrorTimer2Mover"] = "TOP,MirrorTimer1,BOTTOM,0,0"
	E.db["movers"]["MirrorTimer3Mover"] = "TOP,MirrorTimer2,BOTTOM,0,0"
	E.db["movers"]["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325"
	E.db["movers"]["PetAB"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,376"
	E.db["movers"]["PowerBarContainerMover"] = "TOP,ElvUIParent,TOP,0,-76"
	E.db["movers"]["QueueStatusMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-168,-192"
	E.db["movers"]["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-243"
	E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,2"
	E.db["movers"]["ShiftAB"] = "BOTTOM,UIParent,BOTTOM,-238,316"
	E.db["movers"]["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187"
	E.db["movers"]["ThreatBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4"
	E.db["movers"]["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-10,380"
	E.db["movers"]["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-50"
	E.db["movers"]["TorghastChoiceToggle"] = "TOP,UIParent,TOP,-230,-476"
	E.db["movers"]["TotemTrackerMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-385,469"
	E.db["movers"]["VehicleLeaveButton"] = "TOPRIGHT,UIParent,TOPRIGHT,-472,-426"
	E.db["movers"]["VehicleSeatMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-342,-378"
	E.db["movers"]["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,350,-76"
	E.db["movers"]["ZoneAbility"] = "BOTTOM,UIParent,BOTTOM,-230,511"
	E.db["nameplates"]["colors"]["reactions"]["good"]["b"] = 0.29
	E.db["nameplates"]["colors"]["reactions"]["good"]["g"] = 0.67
	E.db["nameplates"]["colors"]["reactions"]["good"]["r"] = 0.3
	E.db["nameplates"]["colors"]["reactions"]["neutral"]["g"] = 0.76
	E.db["nameplates"]["colors"]["selection"][0]["b"] = 0.25
	E.db["nameplates"]["colors"]["selection"][0]["g"] = 0.25
	E.db["nameplates"]["colors"]["selection"][0]["r"] = 0.78
	E.db["nameplates"]["colors"]["selection"][2]["b"] = 0.36
	E.db["nameplates"]["colors"]["selection"][2]["g"] = 0.76
	E.db["nameplates"]["colors"]["selection"][2]["r"] = 0.85
	E.db["nameplates"]["colors"]["selection"][3]["b"] = 0.3
	E.db["nameplates"]["colors"]["selection"][3]["g"] = 0.67
	E.db["nameplates"]["colors"]["selection"][3]["r"] = 0.29
	E.db["nameplates"]["colors"]["threat"]["badColor"]["b"] = 0.25
	E.db["nameplates"]["colors"]["threat"]["badColor"]["g"] = 0.25
	E.db["nameplates"]["colors"]["threat"]["badColor"]["r"] = 0.78
	E.db["nameplates"]["colors"]["threat"]["goodColor"]["b"] = 0.3
	E.db["nameplates"]["colors"]["threat"]["goodColor"]["g"] = 0.67
	E.db["nameplates"]["colors"]["threat"]["goodColor"]["r"] = 0.29
	E.db["nameplates"]["colors"]["threat"]["goodTransition"]["b"] = 0.36
	E.db["nameplates"]["colors"]["threat"]["goodTransition"]["g"] = 0.76
	E.db["nameplates"]["colors"]["threat"]["goodTransition"]["r"] = 0.85
	E.db["nameplates"]["font"] = "Expressway"
	E.db["nameplates"]["units"]["ENEMY_NPC"]["health"]["text"]["format"] = ""
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["health"]["text"]["format"] = ""
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["portrait"]["enable"] = true
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["portrait"]["position"] = "LEFT"
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["portrait"]["xOffset"] = 0
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["portrait"]["yOffset"] = 0
	E.db["tooltip"]["colorAlpha"] = 0.95
	E.db["tooltip"]["font"] = "Expressway"
	E.db["tooltip"]["headerFont"] = "Expressway"
	E.db["tooltip"]["headerFontSize"] = 12
	E.db["tooltip"]["healthBar"]["font"] = "Expressway"
	E.db["tooltip"]["healthBar"]["fontOutline"] = "NONE"
	E.db["tooltip"]["healthBar"]["statusPosition"] = "DISABLED"
	E.db["tooltip"]["itemCount"] = "NONE"
	E.db["tooltip"]["modifierCount"] = false
	E.db["tooltip"]["playerTitles"] = false
	E.db["tooltip"]["showMount"] = false
	E.db["unitframe"]["colors"]["auraBarBuff"]["b"] = 0.039215687662363
	E.db["unitframe"]["colors"]["auraBarBuff"]["g"] = 0.48627454042435
	E.db["unitframe"]["colors"]["auraBarBuff"]["r"] = 1
	E.db["unitframe"]["colors"]["castClassColor"] = true
	E.db["unitframe"]["colors"]["castColor"]["b"] = 0.1
	E.db["unitframe"]["colors"]["castColor"]["g"] = 0.1
	E.db["unitframe"]["colors"]["castColor"]["r"] = 0.1
	E.db["unitframe"]["colors"]["customhealthbackdrop"] = true
	E.db["unitframe"]["colors"]["debuffHighlight"]["Curse"]["a"] = 1
	E.db["unitframe"]["colors"]["debuffHighlight"]["Curse"]["r"] = 0.60000002384186
	E.db["unitframe"]["colors"]["debuffHighlight"]["Disease"]["a"] = 1
	E.db["unitframe"]["colors"]["debuffHighlight"]["Disease"]["g"] = 0.40000003576279
	E.db["unitframe"]["colors"]["debuffHighlight"]["Disease"]["r"] = 0.60000002384186
	E.db["unitframe"]["colors"]["debuffHighlight"]["Magic"]["a"] = 1
	E.db["unitframe"]["colors"]["debuffHighlight"]["Magic"]["g"] = 0.60000002384186
	E.db["unitframe"]["colors"]["debuffHighlight"]["Magic"]["r"] = 0.20000001788139
	E.db["unitframe"]["colors"]["debuffHighlight"]["Poison"]["a"] = 1
	E.db["unitframe"]["colors"]["debuffHighlight"]["Poison"]["g"] = 0.60000002384186
	E.db["unitframe"]["colors"]["frameGlow"]["targetGlow"]["enable"] = false
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["a"] = 1
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["b"] = 1
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["g"] = 0.29411765933037
	E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["a"] = 1
	E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["b"] = 1
	E.db["unitframe"]["colors"]["healPrediction"]["overabsorbs"]["g"] = 0.29411765933037
	E.db["unitframe"]["colors"]["health_backdrop"]["b"] = 0.078431375324726
	E.db["unitframe"]["colors"]["health_backdrop"]["g"] = 0.078431375324726
	E.db["unitframe"]["colors"]["health_backdrop"]["r"] = 0.078431375324726
	E.db["unitframe"]["colors"]["health"]["b"] = 0.098039224743843
	E.db["unitframe"]["colors"]["health"]["g"] = 0.58823531866074
	E.db["unitframe"]["colors"]["health"]["r"] = 0.098039224743843
	E.db["unitframe"]["cooldown"]["checkSeconds"] = true
	E.db["unitframe"]["cooldown"]["fonts"]["enable"] = true
	E.db["unitframe"]["cooldown"]["fonts"]["font"] = "Expressway"
	E.db["unitframe"]["cooldown"]["hideBlizzard"] = true
	E.db["unitframe"]["cooldown"]["reverse"] = true
	E.db["unitframe"]["font"] = "Expressway"
	E.db["unitframe"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["modifiers"]["ALT"] = "Blacklist"
	E.db["unitframe"]["units"]["arena"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["arena"]["buffs"]["priority"] = "Blacklist,CastByUnit,Dispellable,Whitelist,RaidBuffsElvUI"
	E.db["unitframe"]["units"]["arena"]["buffs"]["yOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["font"] = "Emblem"
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["font"] = "Emblem"
	E.db["unitframe"]["units"]["arena"]["castbar"]["height"] = 12
	E.db["unitframe"]["units"]["arena"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["arena"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["arena"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["arena"]["castbar"]["width"] = 200
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["size"] = 14
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["text_format"] = "[name:abbrev]"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["xOffset"] = 2
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Name"]["yOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["attachTextTo"] = "Power"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["size"] = 10
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["text_format"] = "[power:percent]"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Boss Power"]["yOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["size"] = 12
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["text_format"] = "[health:current:shortvalue] || [health:percent]"
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["customTexts"]["Healthpoints"]["yOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["debuffs"]["desaturate"] = true
	E.db["unitframe"]["units"]["arena"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["arena"]["debuffs"]["priority"] = "Blacklist,Boss,Personal,RaidDebuffs,CastByUnit,Whitelist"
	E.db["unitframe"]["units"]["arena"]["healPrediction"]["enable"] = false
	E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["arena"]["height"] = 40
	E.db["unitframe"]["units"]["arena"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["arena"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["arena"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["arena"]["raidicon"]["attachTo"] = "CENTER"
	E.db["unitframe"]["units"]["arena"]["raidicon"]["size"] = 30
	E.db["unitframe"]["units"]["arena"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["spacing"] = 14
	E.db["unitframe"]["units"]["arena"]["width"] = 200
	E.db["unitframe"]["units"]["assist"]["enable"] = false
	E.db["unitframe"]["units"]["boss"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 27
	E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["castbar"]["height"] = 12
	E.db["unitframe"]["units"]["boss"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["boss"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["boss"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 200
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["size"] = 14
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["text_format"] = "[name:abbrev]"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["xOffset"] = 2
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Name"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["attachTextTo"] = "Power"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["size"] = 10
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["text_format"] = "[power:percent]"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Boss Power"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["size"] = 12
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["text_format"] = "[health:current:shortvalue] || [health:percent]"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["Healthpoints"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["boss"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["boss"]["debuffs"]["maxDuration"] = 300
	E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 27
	E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = -16
	E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["height"] = 40
	E.db["unitframe"]["units"]["boss"]["infoPanel"]["height"] = 17
	E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["raidicon"]["attachTo"] = "CENTER"
	E.db["unitframe"]["units"]["boss"]["raidicon"]["size"] = 30
	E.db["unitframe"]["units"]["boss"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["spacing"] = 14
	E.db["unitframe"]["units"]["boss"]["width"] = 200
	E.db["unitframe"]["units"]["focus"]["aurabar"]["detachedWidth"] = 270
	E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 6
	E.db["unitframe"]["units"]["focus"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["focus"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["buffs"]["growthX"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["focus"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["focus"]["buffs"]["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,blockNoDuration,nonPersonal"
	E.db["unitframe"]["units"]["focus"]["buffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontStyle"] = ""
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontStyle"] = ""
	E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 20
	E.db["unitframe"]["units"]["focus"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["focus"]["colorOverride"] = "FORCE_ON"
	E.db["unitframe"]["units"]["focus"]["CombatIcon"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["size"] = 20
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["text_format"] = "[health:current:shortvalue] || [health:percent]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Healthpoints"]["yOffset"] = -8
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["attachTextTo"] = "Power"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["size"] = 12
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["text_format"] = "[power:percent]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Powerpoints"]["yOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["size"] = 15
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["text_format"] = "[classificationcolor][classification]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Classification"]["yOffset"] = 12
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["size"] = 20
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["Target Name"]["yOffset"] = -8
	E.db["unitframe"]["units"]["focus"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["growthX"] = "RIGHT"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["focus"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["focus"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["focus"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["focus"]["disableTargetGlow"] = true
	E.db["unitframe"]["units"]["focus"]["healPrediction"]["absorbStyle"] = "NORMAL"
	E.db["unitframe"]["units"]["focus"]["health"]["attachTextTo"] = "AdditionalPower"
	E.db["unitframe"]["units"]["focus"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["health"]["xOffset"] = 2
	E.db["unitframe"]["units"]["focus"]["height"] = 60
	E.db["unitframe"]["units"]["focus"]["infoPanel"]["height"] = 15
	E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["focus"]["power"]["attachTextTo"] = "InfoPanel"
	E.db["unitframe"]["units"]["focus"]["power"]["height"] = 15
	E.db["unitframe"]["units"]["focus"]["power"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["focus"]["power"]["xOffset"] = -2
	E.db["unitframe"]["units"]["focus"]["raidicon"]["attachTo"] = "CENTER"
	E.db["unitframe"]["units"]["focus"]["raidicon"]["size"] = 30
	E.db["unitframe"]["units"]["focus"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["focus"]["width"] = 250
	E.db["unitframe"]["units"]["focustarget"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["party"]["buffIndicator"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["buffIndicator"]["size"] = 20
	E.db["unitframe"]["units"]["party"]["buffs"]["anchorPoint"] = "TOP"
	E.db["unitframe"]["units"]["party"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["buffs"]["countFontSize"] = 15
	E.db["unitframe"]["units"]["party"]["buffs"]["countYOffset"] = 0
	E.db["unitframe"]["units"]["party"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["party"]["buffs"]["growthY"] = "DOWN"
	E.db["unitframe"]["units"]["party"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 3
	E.db["unitframe"]["units"]["party"]["buffs"]["priority"] = "Whitelist"
	E.db["unitframe"]["units"]["party"]["buffs"]["sizeOverride"] = 30
	E.db["unitframe"]["units"]["party"]["buffs"]["xOffset"] = 30
	E.db["unitframe"]["units"]["party"]["buffs"]["yOffset"] = -40
	E.db["unitframe"]["units"]["party"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["colorOverride"] = "FORCE_OFF"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["enable"] = true
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["size"] = 15
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["text_format"] = "[classcolor][name:long]"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["xOffset"] = 3
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid 2 Name"]["yOffset"] = 14
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["enable"] = true
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["size"] = 15
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["text_format"] = "[classcolor][name:medium]"
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["xOffset"] = 3
	E.db["unitframe"]["units"]["party"]["customTexts"]["Raid Name"]["yOffset"] = 14
	E.db["unitframe"]["units"]["party"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["party"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["debuffs"]["countFontSize"] = 15
	E.db["unitframe"]["units"]["party"]["debuffs"]["countXOffset"] = 1
	E.db["unitframe"]["units"]["party"]["debuffs"]["countYOffset"] = 1
	E.db["unitframe"]["units"]["party"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 3
	E.db["unitframe"]["units"]["party"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["party"]["debuffs"]["sortMethod"] = "NAME"
	E.db["unitframe"]["units"]["party"]["debuffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["party"]["debuffs"]["yOffset"] = 1
	E.db["unitframe"]["units"]["party"]["groupBy"] = "ROLE"
	E.db["unitframe"]["units"]["party"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["party"]["health"]["position"] = "BOTTOM"
	E.db["unitframe"]["units"]["party"]["health"]["text_format"] = "[healthcolor]"
	E.db["unitframe"]["units"]["party"]["health"]["yOffset"] = 2
	E.db["unitframe"]["units"]["party"]["height"] = 47
	E.db["unitframe"]["units"]["party"]["infoPanel"]["height"] = 12
	E.db["unitframe"]["units"]["party"]["name"]["position"] = "TOP"
	E.db["unitframe"]["units"]["party"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["power"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["power"]["yOffset"] = 2
	E.db["unitframe"]["units"]["party"]["privateAuras"]["icon"]["size"] = 18
	E.db["unitframe"]["units"]["party"]["raidicon"]["attachTo"] = "RIGHT"
	E.db["unitframe"]["units"]["party"]["raidicon"]["size"] = 20
	E.db["unitframe"]["units"]["party"]["raidicon"]["xOffset"] = -15
	E.db["unitframe"]["units"]["party"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["scale"] = 1.3
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["xOffset"] = 1
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["yOffset"] = 0
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["party"]["readycheckIcon"]["size"] = 30
	E.db["unitframe"]["units"]["party"]["roleIcon"]["damager"] = false
	E.db["unitframe"]["units"]["party"]["roleIcon"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["party"]["roleIcon"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["roleIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["party"]["summonIcon"]["size"] = 40
	E.db["unitframe"]["units"]["party"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 0
	E.db["unitframe"]["units"]["party"]["width"] = 250
	E.db["unitframe"]["units"]["pet"]["buffs"]["priority"] = "Blacklist,Personal,PlayerBuffs,Dispellable"
	E.db["unitframe"]["units"]["pet"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["pet"]["castbar"]["customTextFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["pet"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["pet"]["castbar"]["customTimeFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 15
	E.db["unitframe"]["units"]["pet"]["castbar"]["iconSize"] = 32
	E.db["unitframe"]["units"]["pet"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["pet"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["pet"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 200
	E.db["unitframe"]["units"]["pet"]["colorOverride"] = "FORCE_ON"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["enable"] = true
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["size"] = 20
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["xOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["customTexts"]["TargetofTarget Name"]["yOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["priority"] = "Blacklist,Personal,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist"
	E.db["unitframe"]["units"]["pet"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["pet"]["healPrediction"]["enable"] = false
	E.db["unitframe"]["units"]["pet"]["height"] = 25
	E.db["unitframe"]["units"]["pet"]["infoPanel"]["height"] = 14
	E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["pet"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["pet"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["pet"]["raidicon"]["xOffset"] = 2
	E.db["unitframe"]["units"]["pet"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["pet"]["width"] = 200
	E.db["unitframe"]["units"]["pettarget"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
	E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 20
	E.db["unitframe"]["units"]["player"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["latency"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 300
	E.db["unitframe"]["units"]["player"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["classbar"]["height"] = 14
	E.db["unitframe"]["units"]["player"]["colorOverride"] = "FORCE_ON"
	E.db["unitframe"]["units"]["player"]["CombatIcon"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["enable"] = true
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["size"] = 20
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["text_format"] = "[curhp]/[maxhp]"
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["customTexts"]["HP"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["player"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["player"]["healPrediction"]["absorbStyle"] = "NORMAL"
	E.db["unitframe"]["units"]["player"]["healPrediction"]["height"] = 35
	E.db["unitframe"]["units"]["player"]["health"]["attachTextTo"] = "AdditionalPower"
	E.db["unitframe"]["units"]["player"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["player"]["height"] = 50
	E.db["unitframe"]["units"]["player"]["infoPanel"]["height"] = 15
	E.db["unitframe"]["units"]["player"]["power"]["attachTextTo"] = "InfoPanel"
	E.db["unitframe"]["units"]["player"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["power"]["height"] = 22
	E.db["unitframe"]["units"]["player"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["raidicon"]["size"] = 30
	E.db["unitframe"]["units"]["player"]["raidicon"]["xOffset"] = 40
	E.db["unitframe"]["units"]["player"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["RestIcon"]["anchorPoint"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["RestIcon"]["size"] = 30
	E.db["unitframe"]["units"]["player"]["RestIcon"]["xOffset"] = 11
	E.db["unitframe"]["units"]["player"]["RestIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["resurrectIcon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["resurrectIcon"]["size"] = 25
	E.db["unitframe"]["units"]["player"]["resurrectIcon"]["xOffset"] = 85
	E.db["unitframe"]["units"]["player"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["player"]["width"] = 371
	E.db["unitframe"]["units"]["raid1"]["buffIndicator"]["size"] = 18
	E.db["unitframe"]["units"]["raid1"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid1"]["buffs"]["countFont"] = "Emblem"
	E.db["unitframe"]["units"]["raid1"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid1"]["buffs"]["growthY"] = "DOWN"
	E.db["unitframe"]["units"]["raid1"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid1"]["buffs"]["priority"] = "Whitelist"
	E.db["unitframe"]["units"]["raid1"]["buffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["raid1"]["buffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid1"]["buffs"]["yOffset"] = -1
	E.db["unitframe"]["units"]["raid1"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["raid1"]["colorOverride"] = "FORCE_OFF"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["enable"] = true
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["size"] = 15
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["text_format"] = "[classcolor][name:medium]"
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["xOffset"] = 3
	E.db["unitframe"]["units"]["raid1"]["customTexts"]["Raid Name"]["yOffset"] = 14
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["countFontSize"] = 15
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["countXOffset"] = 1
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["countYOffset"] = 1
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["sortMethod"] = "NAME"
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid1"]["debuffs"]["yOffset"] = 1
	E.db["unitframe"]["units"]["raid1"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["raid1"]["health"]["text_format"] = "[healthcolor]"
	E.db["unitframe"]["units"]["raid1"]["height"] = 47
	E.db["unitframe"]["units"]["raid1"]["horizontalSpacing"] = 0
	E.db["unitframe"]["units"]["raid1"]["name"]["position"] = "TOP"
	E.db["unitframe"]["units"]["raid1"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid1"]["numGroups"] = 4
	E.db["unitframe"]["units"]["raid1"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["raid1"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["raid1"]["raidicon"]["attachTo"] = "RIGHT"
	E.db["unitframe"]["units"]["raid1"]["raidicon"]["size"] = 20
	E.db["unitframe"]["units"]["raid1"]["raidicon"]["xOffset"] = -15
	E.db["unitframe"]["units"]["raid1"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["scale"] = 1.3
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["xOffset"] = 1
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["enable"] = false
	E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid1"]["readycheckIcon"]["size"] = 30
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["damager"] = false
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid1"]["summonIcon"]["size"] = 40
	E.db["unitframe"]["units"]["raid1"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["raid1"]["verticalSpacing"] = 0
	E.db["unitframe"]["units"]["raid1"]["width"] = 143
	E.db["unitframe"]["units"]["raid2"]["buffIndicator"]["size"] = 16
	E.db["unitframe"]["units"]["raid2"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid2"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["raid2"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["buffs"]["growthY"] = "DOWN"
	E.db["unitframe"]["units"]["raid2"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid2"]["buffs"]["priority"] = "Whitelist"
	E.db["unitframe"]["units"]["raid2"]["buffs"]["sizeOverride"] = 22
	E.db["unitframe"]["units"]["raid2"]["buffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid2"]["buffs"]["yOffset"] = -1
	E.db["unitframe"]["units"]["raid2"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["raid2"]["colorOverride"] = "FORCE_OFF"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["size"] = 13
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["text_format"] = "[classcolor][name:short]"
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["xOffset"] = 3
	E.db["unitframe"]["units"]["raid2"]["customTexts"]["Raid Name"]["yOffset"] = 15
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["countXOffset"] = 1
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["countYOffset"] = 1
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["sizeOverride"] = 22
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["sortMethod"] = "NAME"
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid2"]["debuffs"]["yOffset"] = 1
	E.db["unitframe"]["units"]["raid2"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["raid2"]["health"]["text_format"] = "[healthcolor]"
	E.db["unitframe"]["units"]["raid2"]["height"] = 47
	E.db["unitframe"]["units"]["raid2"]["horizontalSpacing"] = 0
	E.db["unitframe"]["units"]["raid2"]["name"]["position"] = "TOP"
	E.db["unitframe"]["units"]["raid2"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid2"]["numGroups"] = 6
	E.db["unitframe"]["units"]["raid2"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["raid2"]["raidicon"]["attachTo"] = "RIGHT"
	E.db["unitframe"]["units"]["raid2"]["raidicon"]["size"] = 20
	E.db["unitframe"]["units"]["raid2"]["raidicon"]["xOffset"] = -15
	E.db["unitframe"]["units"]["raid2"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["scale"] = 1.3
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["xOffset"] = 1
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid2"]["readycheckIcon"]["size"] = 30
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["damager"] = false
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid2"]["summonIcon"]["size"] = 38
	E.db["unitframe"]["units"]["raid2"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["raid2"]["verticalSpacing"] = 0
	E.db["unitframe"]["units"]["raid2"]["width"] = 95
	E.db["unitframe"]["units"]["raid3"]["buffIndicator"]["size"] = 16
	E.db["unitframe"]["units"]["raid3"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid3"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["raid3"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid3"]["buffs"]["growthY"] = "DOWN"
	E.db["unitframe"]["units"]["raid3"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid3"]["buffs"]["priority"] = "Whitelist"
	E.db["unitframe"]["units"]["raid3"]["buffs"]["sizeOverride"] = 20
	E.db["unitframe"]["units"]["raid3"]["buffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid3"]["buffs"]["yOffset"] = -1
	E.db["unitframe"]["units"]["raid3"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["raid3"]["colorOverride"] = "FORCE_OFF"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["enable"] = true
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["size"] = 14
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["text_format"] = "[classcolor][name:veryshort]"
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid3"]["customTexts"]["Raid Name"]["yOffset"] = 15
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["countXOffset"] = 1
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["countYOffset"] = 1
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["sizeOverride"] = 20
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["sortMethod"] = "NAME"
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["xOffset"] = 2
	E.db["unitframe"]["units"]["raid3"]["debuffs"]["yOffset"] = 1
	E.db["unitframe"]["units"]["raid3"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["raid3"]["health"]["text_format"] = "[healthcolor]"
	E.db["unitframe"]["units"]["raid3"]["height"] = 47
	E.db["unitframe"]["units"]["raid3"]["horizontalSpacing"] = 0
	E.db["unitframe"]["units"]["raid3"]["name"]["position"] = "TOP"
	E.db["unitframe"]["units"]["raid3"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid3"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["raid3"]["raidicon"]["attachTo"] = "RIGHT"
	E.db["unitframe"]["units"]["raid3"]["raidicon"]["size"] = 20
	E.db["unitframe"]["units"]["raid3"]["raidicon"]["xOffset"] = -15
	E.db["unitframe"]["units"]["raid3"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid3"]["raidRoleIcons"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid3"]["raidRoleIcons"]["scale"] = 1.3
	E.db["unitframe"]["units"]["raid3"]["raidRoleIcons"]["xOffset"] = 1
	E.db["unitframe"]["units"]["raid3"]["raidRoleIcons"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["raid3"]["readycheckIcon"]["size"] = 20
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["damager"] = false
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["enable"] = true
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid3"]["roleIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid3"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["raid3"]["verticalSpacing"] = 0
	E.db["unitframe"]["units"]["raid3"]["width"] = 71
	E.db["unitframe"]["units"]["raidpet"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["tank"]["enable"] = false
	E.db["unitframe"]["units"]["tank"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["target"]["buffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontSize"] = 16
	E.db["unitframe"]["units"]["target"]["castbar"]["height"] = 20
	E.db["unitframe"]["units"]["target"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 371
	E.db["unitframe"]["units"]["target"]["colorOverride"] = "FORCE_ON"
	E.db["unitframe"]["units"]["target"]["CombatIcon"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["size"] = 20
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["text_format"] = "[health:current:shortvalue] || [health:percent]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["Healthpoints"]["yOffset"] = -8
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["attachTextTo"] = "Power"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["size"] = 12
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["text_format"] = "[power:percent]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["Powerpoints"]["yOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["size"] = 15
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["text_format"] = "[classificationcolor][classification]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Classification"]["yOffset"] = 12
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["enable"] = true
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["size"] = 20
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["text_format"] = "[name:long][realm:dash]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["Target Name"]["yOffset"] = -8
	E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["attachTo"] = "FRAME"
	E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["target"]["debuffs"]["growthX"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["target"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["target"]["debuffs"]["priority"] = "Blacklist,CastByNPC,CastByUnit,Boss"
	E.db["unitframe"]["units"]["target"]["debuffs"]["sizeOverride"] = 25
	E.db["unitframe"]["units"]["target"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["target"]["fader"]["smooth"] = 0
	E.db["unitframe"]["units"]["target"]["healPrediction"]["absorbStyle"] = "NORMAL"
	E.db["unitframe"]["units"]["target"]["healPrediction"]["height"] = 30
	E.db["unitframe"]["units"]["target"]["health"]["attachTextTo"] = "AdditionalPower"
	E.db["unitframe"]["units"]["target"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 2
	E.db["unitframe"]["units"]["target"]["height"] = 59
	E.db["unitframe"]["units"]["target"]["infoPanel"]["height"] = 15
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["orientation"] = "MIDDLE"
	E.db["unitframe"]["units"]["target"]["phaseIndicator"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["target"]["power"]["attachTextTo"] = "InfoPanel"
	E.db["unitframe"]["units"]["target"]["power"]["height"] = 15
	E.db["unitframe"]["units"]["target"]["power"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = -2
	E.db["unitframe"]["units"]["target"]["raidicon"]["attachTo"] = "CENTER"
	E.db["unitframe"]["units"]["target"]["raidicon"]["size"] = 30
	E.db["unitframe"]["units"]["target"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["target"]["raidRoleIcons"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["resurrectIcon"]["size"] = 25
	E.db["unitframe"]["units"]["target"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["target"]["width"] = 371
	E.db["unitframe"]["units"]["targettarget"]["colorOverride"] = "FORCE_ON"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["enable"] = true
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["font"] = "Expressway"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["size"] = 20
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["xOffset"] = 0
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["TargetofTarget Name"]["yOffset"] = 0
	E.db["unitframe"]["units"]["targettarget"]["debuffs"]["countFont"] = "Expressway"
	E.db["unitframe"]["units"]["targettarget"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["targettarget"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["targettarget"]["height"] = 25
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["xOffset"] = 2
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["targettarget"]["threatStyle"] = "BORDERS"
	E.db["unitframe"]["units"]["targettarget"]["width"] = 163
	E.db["unitframe"]["units"]["targettargettarget"]["threatStyle"] = "BORDERS"
end
